theme: minima

title: Nikolaos Katsilidis Blog
author: Nikolaos Katsilidis
# email:
url: https://nikoskats.github.io

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

description: >
  My thoughts on Deep Learning and Software Engineering as well as my Microsoft Learn Student Ambassadors journey.

# Minima variables
# twitter_username:
github_username: NikosKats
linkedin_username: nikolaos-katsilidis
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
rss: rss

show_excerpts: false

# Used by simple links page
social-links:
  Resume: https://nikoskats.github.io/resume
  LinkedIn: https://www.linkedin.com/in/nikolaos-katsilidis/
  StackOverflow: https://stackoverflow.com/users/7101646/mpesiths
  HackerRank: https://www.hackerrank.com/Nikolaos_Katsil2
  GitHub: https://github.com/NikosKats
  LeetCode: https://leetcode.com/katsilidisn/
  Microsoft: https://studentambassadors.microsoft.com/en-US/profile/40727
  Website: https://nikoskats.github.io

plugin: jekyll-seo-tag
twitter:
  username:
  card: summary_large_image
social:
  name:
  links:
    # - https://twitter.com/
    - https://linkedin.com/in/nikolaos-katsilidis
    - https://github.com/NikosKats

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  - archive.html
  - books.md
  - bookmarks.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

# google_analytics:
#   - UA-185058308-1 # Old GA Universal Analytics property
#   - G-RY6FRPMXHZ # New GA4 property

gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5

# The github repo that is to be used for looking up comments
# comments_repo: chadbaldwin/chadbaldwin.github.io

defaults:
  - scope:
      path: ""
    values:
      image: https://media.licdn.com/dms/image/C4E03AQEhHa5rE7gkwQ/profile-displayphoto-shrink_400_400/0/1552511096541?e=1677110400&v=beta&t=tr5-hCV4O_qB-abo5z6x5BKgqJU9JitAoefMlvt_V6o # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true
